---
title: "Data_pulling"
author: "Kamil_Filipek"
date: "29 marca 2019"
output: html_document
---

## Ściagamy dane ESS
- Dane już są przygotowane i można je znaleźć w tym repozytorium

## Wgrywamy dane
```{r}
library(foreign)

ESS_nPol <- read.spss("/home/kamil/Dokumenty/Edukacja/Zajecia/Statystyka_wprowadzenie/CG_stats/ESS8PL.sav", use.value.labels = F, to.data.frame = T) ## pełne etykiety
ESS_Pol <- read.spss("/home/kamil/Dokumenty/Edukacja/Zajecia/Statystyka_wprowadzenie/CG_stats/ESS8PL.sav", use.value.labels = T, to.data.frame = T) ##bez etykiet

#npol_ger <- read.spss("/home/kamil/Dokumenty/Edukacja/Zajecia/Statystyka_wprowadzenie/CG_stats/polger.sav", use.value.labels = F, to.data.frame = T) ## pełne etykiety
#pol_ger <- read.spss("/home/kamil/Dokumenty/Edukacja/Zajecia/Statystyka_wprowadzenie/CG_stats/polger.sav", use.value.labels = T, to.data.frame = T)

test_dalej
```

### Eksplorujemy zmienne

<<<<<<< HEAD
=======

>>>>>>> 5872d3c29b38573c9577bf142c719dc0038ed588
```{r}
labels <- attributes(ESS_Pol)$variable.labels
write.csv(labels, file="etykiety_ESS.csv")

```

<<<<<<< HEAD
### Zastanawiamy się co będzie efetem naszych zajęć
- Cel
- Podział zadań
- Terminy
- Zaliczenie


### Statystyki opisowe
- Analiza zmiennych - nasz problem badawczy
- Jak wyszukać interesujące nas funkcje statystyczne bez posiadania jakiejkolwiek wiedzy, w których bibliotekach są zlokalizowane?

##### Średnia, mediana, dominanta
```{r}
help("mean") ### argument trim?
help("median")
help("mode")
```




=======
>>>>>>> 5872d3c29b38573c9577bf142c719dc0038ed588
